### ISSUE TITLE
Kdmapper doesn't run unless debug is set to on in bcdedit

### ISSUE THREAD

**Issue by xtremegamer1** [hfiref0x/NtCall64#1]
KdMapper performs exactly as intended when bcdedit -debug on has been used before rebooting. However if debug is set to off it doesn't run.

**Comment by xtremegamer1** [comment]
wait wrong repository

**Comment by hfiref0x** [comment]
I don't have any affiliation with anything called "KdMapper" and this is clearly unrelated to NtCall64.
